# web-service.yml
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  loadBalancerIP: 104.154.187.219
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: web
